# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Run Automation Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Chose automation suite: RegressionSuite or SmokeSuite'
        required: true
        default: SmokeSuite
      browser:
        description: 'Chose browser'
        required: true
        default: chrome
    

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all
      

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Run Automation Suite
      run: mvn clean install -Dci_cd=true -Dbrowser=${{ github.event.inputs.browser }} -DsuiteXmlFile=${{ github.event.inputs.suite }} -PCustomSuite
